
name: 部署文档

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          submodules: true



      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖
        run: |
          corepack enable
          yarn set version stable
          yarn install --frozen-lockfile

      - name: 构建文档
        run: yarn run docs:build

      - name: 部署文档
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/.vuepress/dist
          cname: pterodactyl.top